# Rustfmt configuration for file-scanner project
# See https://rust-lang.github.io/rustfmt/ for options
# Note: Only stable features are used for compatibility

# Edition compatibility
edition = "2021"

# Line length and wrapping
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
reorder_imports = true

# Function and struct formatting
fn_params_layout = "Tall"
fn_call_width = 60
array_width = 60
chain_width = 60

# Control flow formatting
force_explicit_abi = true

# Error handling - using defaults for compatibility

# Trailing elements
match_block_trailing_comma = false

# Newlines and spacing
newline_style = "Unix"

# Advanced formatting
use_small_heuristics = "Default"
remove_nested_parens = true
use_field_init_shorthand = false
use_try_shorthand = false