[package]
name = "file-scanner"
version = "0.1.1"
edition = "2021"
authors = ["File Scanner Project"]

[dependencies]
# Hash calculations
sha2 = "0.10"
md-5 = "0.10"
blake3 = "1.5"

# File metadata and system info
filetime = "0.2"
chrono = { version = "0.4", features = ["serde"] }

# Binary parsing
goblin = "0.10"  # For PE/ELF parsing
object = "0.36" # For object file parsing

# String extraction
regex = "1.10"
encoding_rs = "0.8"

# CLI and output
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# Async runtime (optional, for parallel processing)
tokio = { version = "1.40", features = ["full"] }

# Digital signature verification
ring = "0.17"

# MCP SDK
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", rev = "db03f63", features = ["transport-io"] }
schemars = "0.9"

# HTTP server for MCP
axum = { version = "0.8", features = ["ws"] }
tower = "0.5"
hyper = "1.5"
tokio-stream = "0.1"
futures-util = "0.3"
uuid = { version = "1.0", features = ["v4"] }

# OpenAPI documentation
utoipa = { version = "4.2", features = ["axum_extras", "chrono", "uuid"] }
utoipa-redoc = { version = "6.0", features = ["axum"] }
utoipa-swagger-ui = { version = "9.0", features = ["axum"] }

# Static analysis dependencies
addr2line = "0.24"
memmap2 = "0.9"
capstone = "0.13"
petgraph = "0.8.2"

# Threat detection
yara-x = { git = "https://github.com/wroersma/yara-x", branch = "main" }
walkdir = "2.4"

# Semgrep integration and static analysis enhancements
strsim = "0.11"  # For Levenshtein distance calculations
reqwest = { version = "0.12", features = ["json", "blocking"] }  # For repository checks
git2 = "0.19"  # For Git repository operations
url = "2.5"  # For URL parsing and validation
edit-distance = "2.1"  # Additional string distance algorithms

# OLE and VBA parsing
cfb = "0.10"  # Compound File Binary format (OLE storage)
zip = "3.0"  # For OOXML format support and Java archives

# NPM package analysis
flate2 = "1.0"  # For gzip decompression
tar = "0.4"     # For tar archive extraction

# Java/Android analysis
quick-xml = "0.38"  # For Android manifest parsing
base64 = "0.22"     # For certificate decoding

# PDF analysis - using basic implementation for now
# pdf = "0.9"  # Complex API, may use in future

[dev-dependencies]
tempfile = "3.8"
# Testing utilities
mockall = "0.13"
proptest = "1.4"
rstest = "0.25"
criterion = { version = "0.6", features = ["html_reports"] }
pretty_assertions = "1.4"
test-case = "3.3"
serial_test = "3.0"
predicates = "3.0"
assert_fs = "1.1"
assert_cmd = "2.0"
rand = "0.9"

# For async testing
tokio-test = "0.4"

# For MCP testing
reqwest = { version = "0.12", features = ["json"] }
wiremock = "0.6"

# For shared test fixtures and performance
once_cell = "1.19"

[[bench]]
name = "hash_benchmark"
harness = false

[[bench]]
name = "parser_benchmark"
harness = false

# Test optimization profiles
[profile.test]
opt-level = 2      # Optimize test builds for speed
debug = 1          # Reduce debug info to speed up compilation
incremental = true # Enable incremental compilation
codegen-units = 16 # Parallel codegen

# Fast test configuration for development
[profile.test-fast]
inherits = "test"
opt-level = 3
lto = "thin"
