# Dependabot configuration for automated dependency updates
version: 2
updates:
  # Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "threatflux-team"
    assignees:
      - "threatflux-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group updates by category
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      dev-dependencies:
        patterns:
          - "criterion"
          - "proptest"
          - "rstest"
          - "pretty_assertions"
          - "test-case"
          - "tempfile"
        update-types:
          - "minor"
          - "patch"
      disassembly-engines:
        patterns:
          - "capstone"
          - "iced-x86"
        update-types:
          - "minor"
          - "patch"
      binary-parsing:
        patterns:
          - "goblin"
          - "memmap2"
          - "wasmparser"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "threatflux-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"