version: 2
updates:
  # Enable version updates for Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    # Keep pull requests for security updates open
    open-pull-requests-limit: 10
    # Group updates to reduce noise
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    # Reviewers for dependency updates
    reviewers:
      - "threatflux-team"
    # Labels to apply to dependency PRs
    labels:
      - "dependencies"
      - "automated"
    # Commit message customization
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Allow automatic security updates
    allow:
      - dependency-type: "all"
    # Ignore major version updates for potentially breaking changes
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "threatflux-team"
    labels:
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"