# Cargo configuration
# CI-specific settings are applied via environment variables in the scripts

[build]
# Default build settings for development
# CI environments will override these via CARGO_BUILD_JOBS

[profile.test]
# Default test profile for development
# CI environments will override these settings via environment variables
opt-level = 1
debug = true
incremental = true

# Note: CI-specific settings are applied in scripts/test-parallel-ci.sh via:
# - CARGO_PROFILE_TEST_DEBUG=0
# - CARGO_PROFILE_TEST_CODEGEN_UNITS=1
# - CARGO_PROFILE_TEST_LTO="thin"
# - CARGO_PROFILE_TEST_INCREMENTAL=false