name: Semantic Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vtriple'

    steps:
      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.1.1
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # v1
        with:
          toolchain: 1.87.0

      - name: Install cargo-release
        uses: taiki-e/install-action@65d14c1beefa0eed0e0285f1c6ee9d7c037bc1cf # v2.52.7
        with:
          tool: cargo-release

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'

      - name: Install semantic-release
        run: |
          npm install -g \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            @semantic-release/github@10.3.3 \
            @semantic-release/exec@6.0.3 \
            conventional-changelog-conventionalcommits@8.0.0

      - name: Create semantic-release config
        run: |
          cat > .releaserc.json << 'EOF'
          {
            "branches": ["main", "master"],
            "plugins": [
              ["@semantic-release/commit-analyzer", {
                "preset": "conventionalcommits",
                "releaseRules": [
                  {"type": "feat", "release": "minor"},
                  {"type": "fix", "release": "patch"},
                  {"type": "perf", "release": "patch"},
                  {"type": "deps", "scope": "security", "release": "patch"},
                  {"breaking": true, "release": "major"}
                ]
              }],
              ["@semantic-release/release-notes-generator", {
                "preset": "conventionalcommits",
                "presetConfig": {
                  "types": [
                    {"type": "feat", "section": "Features"},
                    {"type": "fix", "section": "Bug Fixes"},
                    {"type": "perf", "section": "Performance"},
                    {"type": "deps", "section": "Dependencies"},
                    {"type": "docs", "section": "Documentation"},
                    {"type": "ci", "section": "CI/CD"},
                    {"type": "security", "section": "Security"}
                  ]
                }
              }],
              ["@semantic-release/changelog", {
                "changelogFile": "CHANGELOG.md"
              }],
              ["@semantic-release/exec", {
                "prepareCmd": "cargo release version ${nextRelease.version} --no-confirm --execute"
              }],
              ["@semantic-release/git", {
                "assets": ["CHANGELOG.md", "Cargo.toml", "Cargo.lock"],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }],
              ["@semantic-release/github", {
                "successComment": false,
                "failComment": false
              }]
            ]
          }
          EOF

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: npx semantic-release
